name: Update colab badges in notebooks
on: [push]

jobs:
  badges:
    name: Example Badge Job
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout first
        id: checkout
        uses: actions/checkout@v4

      - name: Add/Update badges
        id: badges
        uses: trsvchn/colab-badge-action@v4
      
      - name: Commit and push
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Colab badge added or modified